"""Tamper-evident compliance certificate generator.

The certificate carries a QR code pointing to the inspection id + evidence
hash, so anyone scanning it can verify the report against the live repository
(and detect a forged/edited certificate).
"""
import io
from datetime import datetime
from typing import Dict

import qrcode


def _build_qr_png(payload: str) -> bytes:
    qr = qrcode.QRCode(error_correction=qrcode.constants.ERROR_CORRECT_M, box_size=6, border=2)
    qr.add_data(payload)
    qr.make(fit=True)
    img = qr.make_image(fill_color="black", back_color="white")
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    return buf.getvalue()


def _sanitize(text: str) -> str:
    if not text:
        return ""
    return (str(text)
        .replace('\u20b9', 'Rs.')
        .replace('\u2018', "'").replace('\u2019', "'")
        .replace('\u201c', '"').replace('\u201d', '"')
        .replace('\u2013', '-').replace('\u2014', '-')
        .encode('latin-1', errors='replace')
        .decode('latin-1'))


def build_certificate(result: Dict, verify_base_url: str = "") -> bytes:
    """Generate a certificate PDF (returns pdf bytes)."""
    from fpdf import FPDF

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()

    pdf.set_fill_color(37, 99, 235)
    pdf.rect(0, 0, pdf.w, 26, "F")
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_xy(0, 8)
    pdf.cell(0, 10, "LEGAL METROLOGY COMPLIANCE CERTIFICATE", align="C")
    pdf.ln(6)

    pdf.set_text_color(0, 0, 0)
    score = result.get("compliance_score", 0)
    radar = result.get("compliance_radar") or {}
    grade = radar.get("grade", "D")

    if score >= 80:
        bar_color = (22, 163, 74)
    elif score >= 50:
        bar_color = (234, 179, 8)
    else:
        bar_color = (220, 38, 38)

    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "This product label has been inspected for compliance with the", align="C")
    pdf.ln(5)
    pdf.cell(0, 8, "Legal Metrology (Packaged Commodities) Rules, 2011 (as amended to 2026).", align="C")
    pdf.ln(12)

    pdf.set_font("Helvetica", "", 11)
    key_rows = [
        ("Inspection ID", result.get("inspection_id", "")),
        ("Product", (result.get("declarations") or {}).get("product_name", "") or "—"),
        ("Manufacturer", (result.get("declarations") or {}).get("manufacturer", "") or "—"),
        ("Inspected At", str(result.get("timestamp", "") or "")),
        ("Status", str(result.get("status", "") or "")),
        ("Compliance Score", f"{score}%  (Grade {grade})"),
    ]
    for label, value in key_rows:
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(45, 7, _sanitize(label) + ":", new_x="RIGHT", new_y="LAST")
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 7, _sanitize(value), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    pdf.set_fill_color(*bar_color)
    pdf.rect(30, pdf.get_y() + 2, min(150, (score / 100.0) * 150.0), 6, "F")
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(90, 90, 90)
    pdf.cell(0, 8, "Compliance score bar (0 - 100)", new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(8)

    evidence_hash = ((result.get("evidence") or {}).get("hash")) or result.get("evidence_hash", "")
    payload = f"{verify_base_url}{result.get('inspection_id', '')}|{evidence_hash}"
    qr_bytes = _build_qr_png(payload)
    qr_path = "/tmp/legalmatrix_cert_qr.png"
    import tempfile
    with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as f:
        f.write(qr_bytes)
        qr_path = f.name

    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 6, "Verify authenticity - scan the QR code.", new_x="LMARGIN", new_y="NEXT")
    pdf.image(qr_path, x=pdf.w / 2 - 22, y=pdf.get_y() + 2, w=44)
    pdf.ln(14)

    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 5, f"Evidence SHA-256: {_sanitize(evidence_hash[:48])}...", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)
    pdf.set_font("Helvetica", "I", 8)
    pdf.multi_cell(0, 4,
        "Generated by LegalMatrix. This is an automated preliminary assessment; "
        "final legal opinion rests with the legal metrology authority.",
        new_x="LMARGIN", new_y="NEXT", align="C")

    try:
        import os
        os.unlink(qr_path)
    except OSError:
        pass

    return pdf.output()